config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions
  resources :secrets
  resources :likes

  root 'sessions#new'

end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :secret
end

app/models/secret.rb
class Secret < ActiveRecord::Base
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :users_liked, through: :likes, source: :user

	validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :secrets
	has_many :likes, dependent: :destroy
	has_many :secrets_liked, through: :likes, source: :secret
	has_secure_password

	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
	validates :name, presence: true
	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }

	before_save do
		self.email.downcase!
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	def current_user
		User.find session[:id] if session[:id]
	end

	def require_login
		redirect_to '/sessions/new' if session[:id] == nil
	end

	def require_correct_user
		user = User.find params[:id]
		redirect_to "/users/#{current_user.id}" if current_user != user
	end

	def unlike_button(user, secret)
		Like.where(user: user, secret: secret)
	end

	helper_method :current_user, :unlike_button
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		@user = User.find params[:like][:user_id]
		@secret = Secret.find params[:like][:secret_id]		
		Like.create(user: @user, secret: @secret)
		redirect_to "/secrets"
	end

	def destroy
		like = Like.find params[:id]
		like.destroy if like.user == current_user
		redirect_to "/secrets"
	end

end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
	before_action :require_login, only: [:index, :create, :destroy]

	def index
		@secrets = Secret.all
		@like = Like.new
		user = User.find session[:id]
		@unlike = Like.where(user: user)[0]
	end

	def create
		Secret.create(secret_params)
		redirect_to "/users/#{session[:id]}"
	end

	def destroy
		secret = Secret.find params[:secret][:id]
		secret.destroy if secret.user == current_user
		redirect_to "/users/#{session[:id]}"
	end

	private 
		def secret_params
			params.require(:secret).permit(:content, :user_id)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by email: params[:email]
		if user && user.authenticate(params[:password])
			session[:id] = user.id
			session[:name] = user.name
			redirect_to "/users/#{user.id}"
		else
			flash[:error] = 'Invalid'
			redirect_to "/sessions/new"
		end
	end

	def destroy
		session.clear
		redirect_to "/sessions/new"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login, except: [:new, :create]
	before_action :require_correct_user, only: [:show, :edit, :update, :destroy]

	def new
	end

	def create
		user = User.new
		user.name = params[:name]
		user.email = params[:email]
		user.password = params[:password]
		user.password_confirmation = params[:password_confirmation]
		if user.save
			# redirect_to "/users/#{user.id}"
			redirect_to '/sessions/new'
		else
			flash[:errors] = user.errors.full_messages
			redirect_to '/users/new'
		end
	end

	def show
		@user = User.find params[:id]
		@secret = Secret.new
	end

	def edit
		@user = User.find params[:id]
	end

	def update
		user = User.find params[:id]
		user.name = params[:name]
		user.email = params[:email]
		session[:name] = user.name
		if user.save
			redirect_to "/users/#{user.id}"
		else
			flash[:errors] = user.errors.full_messages
			redirect_to "/users/#{user.id}/edit"
		end		
	end

	def destroy
		user = User.find params[:id]
		user.destroy
		session.clear
		redirect_to '/sessions/new'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secrets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="/secrets">Secrets</a>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><a href="#">Link</a></li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<% if current_user %>
				<li>
					<div class="btn-group">
						<button type="button" class="btn btn-primary"><%= session[:name] %></button>
						<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<span class="caret"></span>
							<span class="sr-only">Toggle Dropdown</span>
						</button>
						<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to "Log Out", session_path(current_user), :method => 'delete' %></li>
						</ul>
					</div>
				</li>
				<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/secrets/index.html.erb
<h1 class='text-center'>Secrets</h1>
<div class='row'>
<% @secrets.each do |s| %>
	<div class='col-sm-6 col-md-4'>
		<div class="bs-callout bs-callout-danger transparent">
		<h3><%= s.content %></h3>
		<p class='blue-color'><%= s.likes.count %> likes</p>
		<% if current_user.secrets_liked.include? s %>
			<%= simple_form_for @unlike, html: {class: 'text-center'}, method: :delete do |f| %>
				<%= f.hidden_field :id, value: unlike_button(s.user, s) %>
				<%= f.button :submit, "Unlike", class: 'btn btn-danger' %>
			<% end %>
		<% else %>
			<%= simple_form_for @like, html: {class: 'text-center'} do |f| %>
				<%= f.hidden_field :user_id, value: session[:id] %>
				<%= f.hidden_field :secret_id, value: s.id %>
				<%= f.button :submit, "Like", class: 'btn btn-primary' %>
			<% end %>
		<% end %>
		<% if current_user == s.user %>
			<%= simple_form_for s, html: {class: 'text-center'}, method: :delete do |f| %>
				<%= f.hidden_field :id, value: s.id %>
				<%= f.button :submit, "Delete", class: 'btn btn-danger' %>
			<% end %>
		<% end %>
		</div>
	</div>
<% end %>
</div>

app/views/users/edit.html.erb
<div class='col-sm-offset-4 col-sm-4 col-md-offset-4 col-md-4 col-lg-offset-4 col-lg-4'>
	<form action='/users/<%= @user.id %>' method='post'>
		<input type='hidden' name='_method' value='patch'>
		<input type='hidden' name='authenticity_token' value="<%= form_authenticity_token %>">
		<div class="form-group">
			<label for="name">Name</label>
			<input type="text" class="form-control" id="name" name="name" placeholder="Name" value='<%= @user.name %>'>
		</div>

		<div class="form-group">
			<label for="email">Email</label>
			<input type="email" class="form-control" id="email" name="email" placeholder="Email" value='<%= @user.email %>'>
		</div>

		<button type="submit" class="btn btn-primary">Update</button>
	</form>
</div>

<% if flash[:errors] %>
	<% flash[:errors].each do |e| %>
		<p><%= e %></p>
	<% end %>
<% end %>

<div class='col-sm-offset-4 col-sm-4 col-md-offset-4 col-md-4 col-lg-offset-4 col-lg-4'>
	<form action='/users/<%= @user.id %>' method='post'>
		<input type='hidden' name='_method' value='delete'>
		<input type='hidden' name='authenticity_token' value="<%= form_authenticity_token %>">

		<input type="submit" class="btn btn-danger" value="Delete Account">
	</form>
</div>

app/views/users/new.html.erb
<div class='col-sm-offset-4 col-sm-4 col-md-offset-4 col-md-4 col-lg-offset-4 col-lg-4'>
<!-- 	<div class="bs-callout bs-callout-primary">
		<h4 class="orange-color">Tired of keeping secrets to yourself?</h4>
		<h4 class="orange-color">Leave them with us!</h4>
	</div>
 -->	<h2 class="text-center">Sign up</h2>
	<form action='/users' method='post'>
		<input type='hidden' name='authenticity_token' value="<%= form_authenticity_token %>">
		<div class="form-group">
			<label for="name">Name</label>
			<input type="text" class="form-control" id="name" name="name" placeholder="Name">
		</div>

		<div class="form-group">
			<label for="email">Email</label>
			<input type="email" class="form-control" id="email" name="email" placeholder="Email">
		</div>

		<div class="form-group">
			<label for="password">Password</label>
			<input type="password" class="form-control" id="password" name="password" placeholder="Password">
		</div>

		<div class="form-group">
			<label for="password_confirmation">Password Confirmation</label>
			<input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Password Confirmation">
		</div>

		<button type="submit" class="btn btn-primary">Join</button>
	</form>
	<div class="bs-callout bs-callout-primary transparent">
		<%= link_to("Already have an account?", new_session_path, {class: "text-primary"}) %>
	</div>
</div>

<% if flash[:errors] %>
	<% flash[:errors].each do |e| %>
		<p><%= e %></p>
	<% end %>
<% end %>

app/views/users/show.html.erb
<% if session[:name] %>
<h4>Welcome back, <%= session[:name] %></h4>
<% end %>

<h1><%= @user.name %></h1>
<a href="/users/<%= @user.id %>/edit">Edit Profile</a>

<div class='row'>
	<div class='col-sm-offset-3 col-sm-6 col-md-offset-3 col-md-6 col-lg-offset-3 col-lg-6'>
		<%= simple_form_for @secret do |f| %>
			<%= f.input :content, label: 'New Secret', placeholder: 'Enter your secret' %>
			<%= f.hidden_field :user_id, value: session[:id] %>
			<%= f.button :submit, "Submit Secret", class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

<div class='row'>
	<div class='col-sm-6 col-md-6 col-lg-6'>
		<h3 class='text-center orange-color'>Your Secrets</h3>
		<% @user.secrets.each do |s| %>
		<div class="bs-callout bs-callout-danger transparent">
			<h3 class='text-center'><%= s.content %></h3>
			<p class='text-center blue-color'><%= s.likes.count %> likes</p>
			<%= simple_form_for s, html: {class: 'text-center'}, method: :delete do |f| %>
				<%= f.hidden_field :id, value: s.id %>
				<%= f.button :submit, "Delete", class: 'btn btn-danger' %>
			<% end %>
		</div>
		<% end %>
	</div>
	<div class='col-sm-6 col-md-6 col-lg-6'>
		<h3 class='text-center orange-color'>Secrets You Liked</h3>
		<% @user.secrets_liked.each do |sl| %>
		<div class="bs-callout bs-callout-success transparent">
		<h3 class='text-center'><%= sl.content %></h3>
		<p class='text-center blue-color'><%= sl.likes.count %> likes</p>
		</div>
		<% end %>
	</div>
</div>